default:
	cd src/ && python3 encryptor.py && zip -r ../dist/crypto-sloppy-encryptor.zip flag.enc encryptor.py
	@echo Challenge compiled.


clean:
	rm -f src/flag.enc
	rm -f dist/crypto-sloppy-encryptor.zip
	@echo Challenge cleaned.
