default:
	cd src/ && zip -r ../dist/RAND0MWARE.zip Alfie_Solomons.pdf , encrypted_1.pdf , encrypted_2.png , RAND0MWARE.exe , pmdk2024_.png
	@echo Challenge compiled.


clean:
	
	rm -f dist/rev-rand0mware.zip
	@echo Challenge cleaned.