default:
	cd src/ && zip -r ../dist/forensics-misleading-secret.zip capture.pcapng
	@echo Challenge compiled.

clean:
	#rm -f src/
	rm -f dist/forensics-misleading-secret.zip
	@echo Challenge cleaned.
