default:
	cd src/ && python3 source.py && zip -r ../dist/crypto-ecguct.zip source.py output.txt
	@echo Challenge compiled.

clean:
	rm -f src/output.txt
	rm -f dist/crypto-ecguct.zip
	@echo Challenge cleaned.
